### PR TITLE
This commit fixes issue 41.

### LINKED ISSUE #41: Misbehaving >> and >>> operators.
## Overview

- (Misbehaving >> and >>> operators) **Bug report.** 

It seems like both operators do a logical right shift rather than a signed one when working with signed wires.

Commit: 835a7

Reproduce steps:

Here is my file: 

```verilog
wire signed[31:0] minus_one = -1; 
wire signed[31:0] left_shifted, test1, test2;
assign left_shifted = minus_one <<< 1;
assign test1 = left_shifted >> 1;
assign test2 = left_shifted >>> 1;

initial begin
  $display("minus_one %d", minus_one);
  $display("left_shifted %d", left_shifted);
  $display("ggt %d gggt %d", test1, test2);
end
```

When I run this, I get the following output:

```
minus_one -1
left_shifted -2
ggt 2147483647 gggt 2147483647
```
 However, I expected the following output: 
```
minus_one -1
left_shifted -2
ggt 2147483647 gggt -1
```

### PR DESCRIPTION
**Pull request by harshgo**
## Overview
This PR fixes the >>> operator by accounting for the fact that in cases
where the length of the register is not divisible by the word size, the topmost
word will be padded by zeroes instead of ones even when the register is signed.

Related issue(s) (if applicable): Fixes #41

### CODE REVIEW

**Comment by harshgo** [comment]
RE: @vmwclbot, I did sign off a5cf5bd

File: src/base/bits/bits.h [hunk 1]
```diff
@@ -1286,19 +1286,25 @@ inline void BitsBase<T, BT, ST>::bitwise_sxr_const(size_t samt, bool arith, Bits
   // Create a mask for extracting the lowest bamt bits from top
   const auto mamt = bits_per_word() - bamt;
   const auto mask = (T(1) << bamt) - 1;
+  // val_ is an array of unsigned values. If we are working with signed values,
+  // we want the top bits of the top-most word to be filled with ones.
+  // This is only used in the case where hob is set and the top word is not
+  // completely full.
+  T upper_most_word = ((-1 << idx) | val_.back());
```
Comment (eschkufz) [inline src/base/bits/bits.h]: Use const and auto wherever possible. Also, to avoid any confusion related to the size of T, use T's constructor when using constants:
```c++
const auto upper_most_word = ((T(-1) << idx) | val_.back());
```

File: src/base/bits/bits.h [hunk 2]
```diff
@@ -1286,19 +1286,25 @@ inline void BitsBase<T, BT, ST>::bitwise_sxr_const(size_t samt, bool arith, Bits
...
 
   // Work our way up until top goes out of range
   size_t w = 0;
   for (size_t t = w+delta, te = val_.size(); t < te; ++w, ++t) {
     if (bamt == 0) {
       res.val_[w] = val_[t];
     } else {
-      res.val_[w] = (val_[t-1] >> bamt) | ((val_[t] & mask) << mamt);
+      T upper_most = (t == val_.size() - 1) ? upper_most_word : val_[t];
```
Comment (eschkufz) [inline src/base/bits/bits.h]: Ditto. Use const auto here:
```
const auto upper_most = // ...
```

**Comment by harshgo** [comment]
Hey @eschkufz, Thank you for your comments. I have made the requested changes.
